### ISSUE TITLE
접속한 유저 수 집계

### ISSUE THREAD

**Issue by userkim12** [project-teamIP/teamIP-BE#20]
### 목표 기능
현재 로그인 중인 유저 수 보여주기

**Comment by giminion** [comment]
- -

**Comment by giminion** [comment]
유효한 리프레시 토큰 개수를 세서 유저수를 집계합니다. 로그아웃 하는 경우 리프레시 토큰이 삭제되지만, 브라우저를 종료하는 경우에는 리프레시 토큰이 삭제되지 않기 때문에 이 부분 해결해야 함. (프론트 쪽..? 백엔드 쪽?)

**Comment by hyun1024** [comment]
액세스 토큰 만료 시 재발급 받기 위해서 리프레시 토큰에 접근하는 경우, 발급이 발생할 때마다 지속적으로 hash값에 시간을 업데이트 후, 마지막 재발급 시간을 기점으로 일정 시간 이상 접근하지 토큰은 현재 사용을 중단한 것으로 간주하고 접속 중인 총 유저 수에 포함되지 않도록 하는 방법이 있을 것 같습니다.
