### ISSUE TITLE
서버를 이중화했을 때 스케줄링 걸린 메서드는 두 번 씩 실행될 것 같다!

### ISSUE THREAD

**Issue by userkim12** [project-teamIP/teamIP-BE#93]
데이터가 똑같은게 두 개씩 생성될 듯 합니다 고쳐보아요

**Comment by hyun1024** [comment]
1. shedLock 라이브러리를 사용해서 스케쥴 락을 거는 방법
2. 이중화 작업 시 외부 메시지 브로커가 필요하기 때문에 kafka를 적용하고, ZooKeeper를 사용하는 과정에서 리더 서버를 선출해서 스케쥴링을 수행하는 방식.
